services:
  app:
    build:
      context: .
      target: production
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--protected-mode", "yes" ]
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
